version: "3.8"

services:
  chatdb:
    image: postgres:15
    container_name: chatdb 
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
